### ISSUE TITLE
Could you share your data

### ISSUE THREAD

**Issue by Tongsun123** [ichatnun/vectorial-TGV-multicontrast-multichannel-MRI#1]
My name is Tong Sun, a Ph.D. student in Shenzhen University in China. At present, I want to achieve TGV algorithm in magnetic resonance electrical property tomography. I search for the related code, and find your search is very helpful to me. I would be appreciated if you could share your data. Thanks! My email is suntong2016@email.szu.edu.cn

**Comment by ichatnun** [comment]
Thank you for showing interest in our work. I have just shared the link to our data to your email.

**Comment by Tongsun123** [comment]
Thanks. But I do not see corresponding link in my email.

**Comment by ichatnun** [comment]
Previously, I shared the link to the data using the Dropbox notification system. I have just sent the link from my email directly. Please check your email once again.
